//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Three_Amigos.BazzarsBazaar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOProducts", Namespace="http://schemas.datacontract.org/2004/07/Three_Amigos.Contracts")]
    [System.SerializableAttribute()]
    public partial class DTOProducts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceForOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceForTenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((this.DescriptionField.Equals(value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ean {
            get {
                return this.EanField;
            }
            set {
                if ((object.ReferenceEquals(this.EanField, value) != true)) {
                    this.EanField = value;
                    this.RaisePropertyChanged("Ean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData")]
        public string ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InStock {
            get {
                return this.InStockField;
            }
            set {
                if ((this.InStockField.Equals(value) != true)) {
                    this.InStockField = value;
                    this.RaisePropertyChanged("InStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForOne {
            get {
                return this.PriceForOneField;
            }
            set {
                if ((this.PriceForOneField.Equals(value) != true)) {
                    this.PriceForOneField = value;
                    this.RaisePropertyChanged("PriceForOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForTen {
            get {
                return this.PriceForTenField;
            }
            set {
                if ((this.PriceForTenField.Equals(value) != true)) {
                    this.PriceForTenField = value;
                    this.RaisePropertyChanged("PriceForTen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOCategories", Namespace="http://schemas.datacontract.org/2004/07/Three_Amigos.Contracts")]
    [System.SerializableAttribute()]
    public partial class DTOCategories : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableProductCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableProductCount {
            get {
                return this.AvailableProductCountField;
            }
            set {
                if ((this.AvailableProductCountField.Equals(value) != true)) {
                    this.AvailableProductCountField = value;
                    this.RaisePropertyChanged("AvailableProductCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((this.DescriptionField.Equals(value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData")]
        public int ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((this.ExtensionData1Field.Equals(value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BazzarsBazaar.ServiceContract")]
    public interface ServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceContract/GetProductById", ReplyAction="http://tempuri.org/ServiceContract/GetProductByIdResponse")]
        Three_Amigos.BazzarsBazaar.DTOProducts GetProductById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceContract/GetProductById", ReplyAction="http://tempuri.org/ServiceContract/GetProductByIdResponse")]
        System.Threading.Tasks.Task<Three_Amigos.BazzarsBazaar.DTOProducts> GetProductByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceContract/GetCategories", ReplyAction="http://tempuri.org/ServiceContract/GetCategoriesResponse")]
        Three_Amigos.BazzarsBazaar.DTOCategories[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceContract/GetCategories", ReplyAction="http://tempuri.org/ServiceContract/GetCategoriesResponse")]
        System.Threading.Tasks.Task<Three_Amigos.BazzarsBazaar.DTOCategories[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceContract/GetCategoriesById", ReplyAction="http://tempuri.org/ServiceContract/GetCategoriesByIdResponse")]
        Three_Amigos.BazzarsBazaar.DTOCategories GetCategoriesById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceContract/GetCategoriesById", ReplyAction="http://tempuri.org/ServiceContract/GetCategoriesByIdResponse")]
        System.Threading.Tasks.Task<Three_Amigos.BazzarsBazaar.DTOCategories> GetCategoriesByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceContractChannel : Three_Amigos.BazzarsBazaar.ServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceContractClient : System.ServiceModel.ClientBase<Three_Amigos.BazzarsBazaar.ServiceContract>, Three_Amigos.BazzarsBazaar.ServiceContract {
        
        public ServiceContractClient() {
        }
        
        public ServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Three_Amigos.BazzarsBazaar.DTOProducts GetProductById(int Id) {
            return base.Channel.GetProductById(Id);
        }
        
        public System.Threading.Tasks.Task<Three_Amigos.BazzarsBazaar.DTOProducts> GetProductByIdAsync(int Id) {
            return base.Channel.GetProductByIdAsync(Id);
        }
        
        public Three_Amigos.BazzarsBazaar.DTOCategories[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<Three_Amigos.BazzarsBazaar.DTOCategories[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public Three_Amigos.BazzarsBazaar.DTOCategories GetCategoriesById(int Id) {
            return base.Channel.GetCategoriesById(Id);
        }
        
        public System.Threading.Tasks.Task<Three_Amigos.BazzarsBazaar.DTOCategories> GetCategoriesByIdAsync(int Id) {
            return base.Channel.GetCategoriesByIdAsync(Id);
        }
    }
}
