//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeAmigosStoreServices.BazzasBazaar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableProductCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableProductCount {
            get {
                return this.AvailableProductCountField;
            }
            set {
                if ((this.AvailableProductCountField.Equals(value) != true)) {
                    this.AvailableProductCountField = value;
                    this.RaisePropertyChanged("AvailableProductCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpectedRestockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceForOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceForTenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ean {
            get {
                return this.EanField;
            }
            set {
                if ((object.ReferenceEquals(this.EanField, value) != true)) {
                    this.EanField = value;
                    this.RaisePropertyChanged("Ean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpectedRestock {
            get {
                return this.ExpectedRestockField;
            }
            set {
                if ((this.ExpectedRestockField.Equals(value) != true)) {
                    this.ExpectedRestockField = value;
                    this.RaisePropertyChanged("ExpectedRestock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InStock {
            get {
                return this.InStockField;
            }
            set {
                if ((this.InStockField.Equals(value) != true)) {
                    this.InStockField = value;
                    this.RaisePropertyChanged("InStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForOne {
            get {
                return this.PriceForOneField;
            }
            set {
                if ((this.PriceForOneField.Equals(value) != true)) {
                    this.PriceForOneField = value;
                    this.RaisePropertyChanged("PriceForOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForTen {
            get {
                return this.PriceForTenField;
            }
            set {
                if ((this.PriceForTenField.Equals(value) != true)) {
                    this.PriceForTenField = value;
                    this.RaisePropertyChanged("PriceForTen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductEanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WhenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductEan {
            get {
                return this.ProductEanField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductEanField, value) != true)) {
                    this.ProductEanField = value;
                    this.RaisePropertyChanged("ProductEan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime When {
            get {
                return this.WhenField;
            }
            set {
                if ((this.WhenField.Equals(value) != true)) {
                    this.WhenField = value;
                    this.RaisePropertyChanged("When");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BazzasBazaar.IStore")]
    public interface IStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetAllCategories", ReplyAction="http://tempuri.org/IStore/GetAllCategoriesResponse")]
        ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesResponse GetAllCategories(ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStore/GetAllCategories", ReplyAction="http://tempuri.org/IStore/GetAllCategoriesResponse")]
        System.IAsyncResult BeginGetAllCategories(ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest request, System.AsyncCallback callback, object asyncState);
        
        ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesResponse EndGetAllCategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetCategoryById", ReplyAction="http://tempuri.org/IStore/GetCategoryByIdResponse")]
        ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdResponse GetCategoryById(ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStore/GetCategoryById", ReplyAction="http://tempuri.org/IStore/GetCategoryByIdResponse")]
        System.IAsyncResult BeginGetCategoryById(ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest request, System.AsyncCallback callback, object asyncState);
        
        ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdResponse EndGetCategoryById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetFilteredProducts", ReplyAction="http://tempuri.org/IStore/GetFilteredProductsResponse")]
        ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsResponse GetFilteredProducts(ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStore/GetFilteredProducts", ReplyAction="http://tempuri.org/IStore/GetFilteredProductsResponse")]
        System.IAsyncResult BeginGetFilteredProducts(ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest request, System.AsyncCallback callback, object asyncState);
        
        ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsResponse EndGetFilteredProducts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetProductById", ReplyAction="http://tempuri.org/IStore/GetProductByIdResponse")]
        ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdResponse GetProductById(ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStore/GetProductById", ReplyAction="http://tempuri.org/IStore/GetProductByIdResponse")]
        System.IAsyncResult BeginGetProductById(ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest request, System.AsyncCallback callback, object asyncState);
        
        ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdResponse EndGetProductById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetOrderById", ReplyAction="http://tempuri.org/IStore/GetOrderByIdResponse")]
        ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdResponse GetOrderById(ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStore/GetOrderById", ReplyAction="http://tempuri.org/IStore/GetOrderByIdResponse")]
        System.IAsyncResult BeginGetOrderById(ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest request, System.AsyncCallback callback, object asyncState);
        
        ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdResponse EndGetOrderById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CreateOrder", ReplyAction="http://tempuri.org/IStore/CreateOrderResponse")]
        ThreeAmigosStoreServices.BazzasBazaar.CreateOrderResponse CreateOrder(ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStore/CreateOrder", ReplyAction="http://tempuri.org/IStore/CreateOrderResponse")]
        System.IAsyncResult BeginCreateOrder(ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        ThreeAmigosStoreServices.BazzasBazaar.CreateOrderResponse EndCreateOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CancelOrderById", ReplyAction="http://tempuri.org/IStore/CancelOrderByIdResponse")]
        ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdResponse CancelOrderById(ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStore/CancelOrderById", ReplyAction="http://tempuri.org/IStore/CancelOrderByIdResponse")]
        System.IAsyncResult BeginCancelOrderById(ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest request, System.AsyncCallback callback, object asyncState);
        
        ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdResponse EndCancelOrderById(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCategories", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllCategoriesRequest {
        
        public GetAllCategoriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCategoriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ThreeAmigosStoreServices.BazzasBazaar.Category[] GetAllCategoriesResult;
        
        public GetAllCategoriesResponse() {
        }
        
        public GetAllCategoriesResponse(ThreeAmigosStoreServices.BazzasBazaar.Category[] GetAllCategoriesResult) {
            this.GetAllCategoriesResult = GetAllCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCategoryById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCategoryByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetCategoryByIdRequest() {
        }
        
        public GetCategoryByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCategoryByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCategoryByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ThreeAmigosStoreServices.BazzasBazaar.Category GetCategoryByIdResult;
        
        public GetCategoryByIdResponse() {
        }
        
        public GetCategoryByIdResponse(ThreeAmigosStoreServices.BazzasBazaar.Category GetCategoryByIdResult) {
            this.GetCategoryByIdResult = GetCategoryByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilteredProducts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilteredProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> categoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<double> minPrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<double> maxPrice;
        
        public GetFilteredProductsRequest() {
        }
        
        public GetFilteredProductsRequest(System.Nullable<int> categoryId, string categoryName, System.Nullable<double> minPrice, System.Nullable<double> maxPrice) {
            this.categoryId = categoryId;
            this.categoryName = categoryName;
            this.minPrice = minPrice;
            this.maxPrice = maxPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilteredProductsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilteredProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ThreeAmigosStoreServices.BazzasBazaar.Product[] GetFilteredProductsResult;
        
        public GetFilteredProductsResponse() {
        }
        
        public GetFilteredProductsResponse(ThreeAmigosStoreServices.BazzasBazaar.Product[] GetFilteredProductsResult) {
            this.GetFilteredProductsResult = GetFilteredProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetProductByIdRequest() {
        }
        
        public GetProductByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ThreeAmigosStoreServices.BazzasBazaar.Product GetProductByIdResult;
        
        public GetProductByIdResponse() {
        }
        
        public GetProductByIdResponse(ThreeAmigosStoreServices.BazzasBazaar.Product GetProductByIdResult) {
            this.GetProductByIdResult = GetProductByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrderByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetOrderByIdRequest() {
        }
        
        public GetOrderByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrderByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ThreeAmigosStoreServices.BazzasBazaar.Order GetOrderByIdResult;
        
        public GetOrderByIdResponse() {
        }
        
        public GetOrderByIdResponse(ThreeAmigosStoreServices.BazzasBazaar.Order GetOrderByIdResult) {
            this.GetOrderByIdResult = GetOrderByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string accountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cardNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int productId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int quantity;
        
        public CreateOrderRequest() {
        }
        
        public CreateOrderRequest(string accountName, string cardNumber, int productId, int quantity) {
            this.accountName = accountName;
            this.cardNumber = cardNumber;
            this.productId = productId;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ThreeAmigosStoreServices.BazzasBazaar.Order CreateOrderResult;
        
        public CreateOrderResponse() {
        }
        
        public CreateOrderResponse(ThreeAmigosStoreServices.BazzasBazaar.Order CreateOrderResult) {
            this.CreateOrderResult = CreateOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelOrderById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelOrderByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public CancelOrderByIdRequest() {
        }
        
        public CancelOrderByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelOrderByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelOrderByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CancelOrderByIdResult;
        
        public CancelOrderByIdResponse() {
        }
        
        public CancelOrderByIdResponse(bool CancelOrderByIdResult) {
            this.CancelOrderByIdResult = CancelOrderByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreChannel : ThreeAmigosStoreServices.BazzasBazaar.IStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCategoryByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCategoryByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFilteredProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFilteredProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrderByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrderByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.CreateOrderResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ThreeAmigosStoreServices.BazzasBazaar.CreateOrderResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CancelOrderByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CancelOrderByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreClient : System.ServiceModel.ClientBase<ThreeAmigosStoreServices.BazzasBazaar.IStore>, ThreeAmigosStoreServices.BazzasBazaar.IStore {
        
        private BeginOperationDelegate onBeginGetAllCategoriesDelegate;
        
        private EndOperationDelegate onEndGetAllCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCategoryByIdDelegate;
        
        private EndOperationDelegate onEndGetCategoryByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetCategoryByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFilteredProductsDelegate;
        
        private EndOperationDelegate onEndGetFilteredProductsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFilteredProductsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductByIdDelegate;
        
        private EndOperationDelegate onEndGetProductByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrderByIdDelegate;
        
        private EndOperationDelegate onEndGetOrderByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrderByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateOrderDelegate;
        
        private EndOperationDelegate onEndCreateOrderDelegate;
        
        private System.Threading.SendOrPostCallback onCreateOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginCancelOrderByIdDelegate;
        
        private EndOperationDelegate onEndCancelOrderByIdDelegate;
        
        private System.Threading.SendOrPostCallback onCancelOrderByIdCompletedDelegate;
        
        public StoreClient() {
        }
        
        public StoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAllCategoriesCompletedEventArgs> GetAllCategoriesCompleted;
        
        public event System.EventHandler<GetCategoryByIdCompletedEventArgs> GetCategoryByIdCompleted;
        
        public event System.EventHandler<GetFilteredProductsCompletedEventArgs> GetFilteredProductsCompleted;
        
        public event System.EventHandler<GetProductByIdCompletedEventArgs> GetProductByIdCompleted;
        
        public event System.EventHandler<GetOrderByIdCompletedEventArgs> GetOrderByIdCompleted;
        
        public event System.EventHandler<CreateOrderCompletedEventArgs> CreateOrderCompleted;
        
        public event System.EventHandler<CancelOrderByIdCompletedEventArgs> CancelOrderByIdCompleted;
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesResponse GetAllCategories(ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest request) {
            return base.Channel.GetAllCategories(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllCategories(ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllCategories(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesResponse EndGetAllCategories(System.IAsyncResult result) {
            return base.Channel.EndGetAllCategories(result);
        }
        
        private System.IAsyncResult OnBeginGetAllCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest request = ((ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest)(inValues[0]));
            return this.BeginGetAllCategories(request, callback, asyncState);
        }
        
        private object[] OnEndGetAllCategories(System.IAsyncResult result) {
            ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesResponse retVal = this.EndGetAllCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCategoriesCompleted(object state) {
            if ((this.GetAllCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCategoriesCompleted(this, new GetAllCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllCategoriesAsync(ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest request) {
            this.GetAllCategoriesAsync(request, null);
        }
        
        public void GetAllCategoriesAsync(ThreeAmigosStoreServices.BazzasBazaar.GetAllCategoriesRequest request, object userState) {
            if ((this.onBeginGetAllCategoriesDelegate == null)) {
                this.onBeginGetAllCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetAllCategories);
            }
            if ((this.onEndGetAllCategoriesDelegate == null)) {
                this.onEndGetAllCategoriesDelegate = new EndOperationDelegate(this.OnEndGetAllCategories);
            }
            if ((this.onGetAllCategoriesCompletedDelegate == null)) {
                this.onGetAllCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllCategoriesDelegate, new object[] {
                        request}, this.onEndGetAllCategoriesDelegate, this.onGetAllCategoriesCompletedDelegate, userState);
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdResponse GetCategoryById(ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest request) {
            return base.Channel.GetCategoryById(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCategoryById(ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCategoryById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdResponse EndGetCategoryById(System.IAsyncResult result) {
            return base.Channel.EndGetCategoryById(result);
        }
        
        private System.IAsyncResult OnBeginGetCategoryById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest request = ((ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest)(inValues[0]));
            return this.BeginGetCategoryById(request, callback, asyncState);
        }
        
        private object[] OnEndGetCategoryById(System.IAsyncResult result) {
            ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdResponse retVal = this.EndGetCategoryById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCategoryByIdCompleted(object state) {
            if ((this.GetCategoryByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCategoryByIdCompleted(this, new GetCategoryByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCategoryByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest request) {
            this.GetCategoryByIdAsync(request, null);
        }
        
        public void GetCategoryByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.GetCategoryByIdRequest request, object userState) {
            if ((this.onBeginGetCategoryByIdDelegate == null)) {
                this.onBeginGetCategoryByIdDelegate = new BeginOperationDelegate(this.OnBeginGetCategoryById);
            }
            if ((this.onEndGetCategoryByIdDelegate == null)) {
                this.onEndGetCategoryByIdDelegate = new EndOperationDelegate(this.OnEndGetCategoryById);
            }
            if ((this.onGetCategoryByIdCompletedDelegate == null)) {
                this.onGetCategoryByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCategoryByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetCategoryByIdDelegate, new object[] {
                        request}, this.onEndGetCategoryByIdDelegate, this.onGetCategoryByIdCompletedDelegate, userState);
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsResponse GetFilteredProducts(ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest request) {
            return base.Channel.GetFilteredProducts(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFilteredProducts(ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFilteredProducts(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsResponse EndGetFilteredProducts(System.IAsyncResult result) {
            return base.Channel.EndGetFilteredProducts(result);
        }
        
        private System.IAsyncResult OnBeginGetFilteredProducts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest request = ((ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest)(inValues[0]));
            return this.BeginGetFilteredProducts(request, callback, asyncState);
        }
        
        private object[] OnEndGetFilteredProducts(System.IAsyncResult result) {
            ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsResponse retVal = this.EndGetFilteredProducts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFilteredProductsCompleted(object state) {
            if ((this.GetFilteredProductsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFilteredProductsCompleted(this, new GetFilteredProductsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFilteredProductsAsync(ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest request) {
            this.GetFilteredProductsAsync(request, null);
        }
        
        public void GetFilteredProductsAsync(ThreeAmigosStoreServices.BazzasBazaar.GetFilteredProductsRequest request, object userState) {
            if ((this.onBeginGetFilteredProductsDelegate == null)) {
                this.onBeginGetFilteredProductsDelegate = new BeginOperationDelegate(this.OnBeginGetFilteredProducts);
            }
            if ((this.onEndGetFilteredProductsDelegate == null)) {
                this.onEndGetFilteredProductsDelegate = new EndOperationDelegate(this.OnEndGetFilteredProducts);
            }
            if ((this.onGetFilteredProductsCompletedDelegate == null)) {
                this.onGetFilteredProductsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFilteredProductsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFilteredProductsDelegate, new object[] {
                        request}, this.onEndGetFilteredProductsDelegate, this.onGetFilteredProductsCompletedDelegate, userState);
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdResponse GetProductById(ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest request) {
            return base.Channel.GetProductById(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetProductById(ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdResponse EndGetProductById(System.IAsyncResult result) {
            return base.Channel.EndGetProductById(result);
        }
        
        private System.IAsyncResult OnBeginGetProductById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest request = ((ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest)(inValues[0]));
            return this.BeginGetProductById(request, callback, asyncState);
        }
        
        private object[] OnEndGetProductById(System.IAsyncResult result) {
            ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdResponse retVal = this.EndGetProductById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductByIdCompleted(object state) {
            if ((this.GetProductByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductByIdCompleted(this, new GetProductByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest request) {
            this.GetProductByIdAsync(request, null);
        }
        
        public void GetProductByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.GetProductByIdRequest request, object userState) {
            if ((this.onBeginGetProductByIdDelegate == null)) {
                this.onBeginGetProductByIdDelegate = new BeginOperationDelegate(this.OnBeginGetProductById);
            }
            if ((this.onEndGetProductByIdDelegate == null)) {
                this.onEndGetProductByIdDelegate = new EndOperationDelegate(this.OnEndGetProductById);
            }
            if ((this.onGetProductByIdCompletedDelegate == null)) {
                this.onGetProductByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductByIdDelegate, new object[] {
                        request}, this.onEndGetProductByIdDelegate, this.onGetProductByIdCompletedDelegate, userState);
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdResponse GetOrderById(ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest request) {
            return base.Channel.GetOrderById(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOrderById(ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrderById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdResponse EndGetOrderById(System.IAsyncResult result) {
            return base.Channel.EndGetOrderById(result);
        }
        
        private System.IAsyncResult OnBeginGetOrderById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest request = ((ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest)(inValues[0]));
            return this.BeginGetOrderById(request, callback, asyncState);
        }
        
        private object[] OnEndGetOrderById(System.IAsyncResult result) {
            ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdResponse retVal = this.EndGetOrderById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrderByIdCompleted(object state) {
            if ((this.GetOrderByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrderByIdCompleted(this, new GetOrderByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrderByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest request) {
            this.GetOrderByIdAsync(request, null);
        }
        
        public void GetOrderByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.GetOrderByIdRequest request, object userState) {
            if ((this.onBeginGetOrderByIdDelegate == null)) {
                this.onBeginGetOrderByIdDelegate = new BeginOperationDelegate(this.OnBeginGetOrderById);
            }
            if ((this.onEndGetOrderByIdDelegate == null)) {
                this.onEndGetOrderByIdDelegate = new EndOperationDelegate(this.OnEndGetOrderById);
            }
            if ((this.onGetOrderByIdCompletedDelegate == null)) {
                this.onGetOrderByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrderByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrderByIdDelegate, new object[] {
                        request}, this.onEndGetOrderByIdDelegate, this.onGetOrderByIdCompletedDelegate, userState);
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.CreateOrderResponse CreateOrder(ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest request) {
            return base.Channel.CreateOrder(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreateOrder(ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ThreeAmigosStoreServices.BazzasBazaar.CreateOrderResponse EndCreateOrder(System.IAsyncResult result) {
            return base.Channel.EndCreateOrder(result);
        }
        
        private System.IAsyncResult OnBeginCreateOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest request = ((ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest)(inValues[0]));
            return this.BeginCreateOrder(request, callback, asyncState);
        }
        
        private object[] OnEndCreateOrder(System.IAsyncResult result) {
            ThreeAmigosStoreServices.BazzasBazaar.CreateOrderResponse retVal = this.EndCreateOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateOrderCompleted(object state) {
            if ((this.CreateOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateOrderCompleted(this, new CreateOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateOrderAsync(ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest request) {
            this.CreateOrderAsync(request, null);
        }
        
        public void CreateOrderAsync(ThreeAmigosStoreServices.BazzasBazaar.CreateOrderRequest request, object userState) {
            if ((this.onBeginCreateOrderDelegate == null)) {
                this.onBeginCreateOrderDelegate = new BeginOperationDelegate(this.OnBeginCreateOrder);
            }
            if ((this.onEndCreateOrderDelegate == null)) {
                this.onEndCreateOrderDelegate = new EndOperationDelegate(this.OnEndCreateOrder);
            }
            if ((this.onCreateOrderCompletedDelegate == null)) {
                this.onCreateOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateOrderCompleted);
            }
            base.InvokeAsync(this.onBeginCreateOrderDelegate, new object[] {
                        request}, this.onEndCreateOrderDelegate, this.onCreateOrderCompletedDelegate, userState);
        }
        
        public ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdResponse CancelOrderById(ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest request) {
            return base.Channel.CancelOrderById(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCancelOrderById(ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCancelOrderById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdResponse EndCancelOrderById(System.IAsyncResult result) {
            return base.Channel.EndCancelOrderById(result);
        }
        
        private System.IAsyncResult OnBeginCancelOrderById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest request = ((ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest)(inValues[0]));
            return this.BeginCancelOrderById(request, callback, asyncState);
        }
        
        private object[] OnEndCancelOrderById(System.IAsyncResult result) {
            ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdResponse retVal = this.EndCancelOrderById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCancelOrderByIdCompleted(object state) {
            if ((this.CancelOrderByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CancelOrderByIdCompleted(this, new CancelOrderByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CancelOrderByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest request) {
            this.CancelOrderByIdAsync(request, null);
        }
        
        public void CancelOrderByIdAsync(ThreeAmigosStoreServices.BazzasBazaar.CancelOrderByIdRequest request, object userState) {
            if ((this.onBeginCancelOrderByIdDelegate == null)) {
                this.onBeginCancelOrderByIdDelegate = new BeginOperationDelegate(this.OnBeginCancelOrderById);
            }
            if ((this.onEndCancelOrderByIdDelegate == null)) {
                this.onEndCancelOrderByIdDelegate = new EndOperationDelegate(this.OnEndCancelOrderById);
            }
            if ((this.onCancelOrderByIdCompletedDelegate == null)) {
                this.onCancelOrderByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCancelOrderByIdCompleted);
            }
            base.InvokeAsync(this.onBeginCancelOrderByIdDelegate, new object[] {
                        request}, this.onEndCancelOrderByIdDelegate, this.onCancelOrderByIdCompletedDelegate, userState);
        }
    }
}
